# Generated by Django 4.1.2 on 2022-11-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificados',
            old_name='id_validacion',
            new_name='id_verificacion',
        ),
    ]
